[tasks.dev]
dependencies = ["install-commands"]
command = "trunk"
args = ["--config", "Trunk.toml", "serve", "frontend/index.html"]
workspace = false

[tasks.bundle]
dependencies = ["install-commands"]
command = "trunk"
args = ["--config", "Trunk.toml", "build", "--release", "frontend/index.html"]
workspace = false

[tasks.tauri-bundle]
dependencies = ["install-commands"]
command = "cargo-tauri"
args = ["build"]
workspace = false

[tasks.tauri-dev]
dependencies = ["install-commands"]
command = "cargo-tauri"
args = ["dev"]
workspace = false

[tasks.css]
dependencies = ["npm-install"]
script = "npx tailwindcss -i frontend/public/css/main.css -o frontend/public/css/main_compiled.css"
workspace = false

[tasks.npm-install]
script = "npm install"

[tasks.install-commands]
dependencies = ["install-trunk", "install-wasm-bindgen-cli", "install-tauri-cli"]

[tasks.install-trunk]
install_crate = { crate_name = "trunk" }

[tasks.install-wasm-bindgen-cli]
install_crate = { crate_name = "wasm-bindgen-cli" }

[tasks.install-tauri-cli]
command = "cargo"
args = ["install", "tauri-cli", "--locked", "--version", "^1.0.0-rc"]
